apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo
  name: demo-boot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - image: duweiduwais/demo:v1
          imagePullPolicy: IfNotPresent
          name: demo
---
apiVersion: v1
kind: Service
metadata:
  name: demo-boot
spec:
  selector:
    app: demo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080